# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPzoc8EamEy4bSjBeLAMYxZUbPEkXMrx
"""
import streamlit as st
import pandas as pd
st.write("file_path =", file_path)
st.write("Does file exist?", os.path.exists(file_path))
dataset = pd.read_excel(file_path)
dataset=pd.read_excel("395k0As85_Text_When Brands Take Sides Public Reactions to Political Advertising_43_43.xlsx")

x=dataset.drop(['7. Which advertisement appeals to you the most?'], axis=1)

y=dataset['7. Which advertisement appeals to you the most?']

from sklearn.model_selection import train_test_split
# Ensure x and y are derived from a consistent source, e.g., the 'data' DataFrame
x = dataset.drop('responded', axis=1)
y = dataset['responded']
x_train, x_test, y_train, y_test = train_test_split(x,y , test_size=0.2)

import tensorflow as tf
model=tf.keras.models.Sequential()

import tensorflow as tf
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(x_train.shape[1],)),
    tf.keras.layers.Dense(256, activation='sigmoid'),
    tf.keras.layers.Dense(256, activation='sigmoid'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1000)

model.evaluate(x_test, y_test)

